name = "Nelly's Pack O' Shit"
author = "jammeh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb94822ef0ba81674d0ad7bbb4b76a38dd2e795eb232e4fadf2fa23cd0e710c7"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
