name = "Nelly's Pack O' Shit"
author = "jammehcow"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e791413666693d7a9f1c916bab27cd87a6222e7a9a07fe3aef7b0a1dbf40a12"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
