name = "Nelly's Pack O' Shit"
author = "jammehcow"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ba6f100b9f86584d31440dfbb486d51eaaf0434a20131e5f4e9f7848ac869ba"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
