name = "Nelly's Pack O' Shit"
author = "jammehcow"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df2ff79c7a3cee607b173c9032c9c9e7ec40961771452179342b3a1e55192dc"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
