name = "Nelly's Pack O' Shit"
author = "jammeh"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "473fcb33965f2d23954bf95aa006f55143a9b366e17320df168883191b87b5b6"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
