name = "Nelly's Pack O' Shit"
author = "jammehcow"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce4e15bda56a343adcfe656a01505337429f2904909b9a49d68387d409c2df3"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
