name = "Nelly's Pack O' Shit"
author = "jammehcow"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb915672d3a74b59342a9b54d9cccb51aa82df9ee8a5fb0c8f8a53e9d565bd03"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
