name = "Nelly's Pack O' Shit"
author = "jammehcow"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9318e3bd5f95aaa7a39cb187ad015c125cbe41a3cd382143d512784045f14b0"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
