name = "Nelly's Pack O' Shit"
author = "jammeh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb7b77de9b22155777e4509823ab33897652c26e72d5301821842892be13be70"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
