name = "Nelly's Pack O' Shit"
author = "jammeh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4e5e16f18f2b5f8a48018383423a6bf9a12948d5ccb89497f46c0bd368273d6"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
