name = "Nelly's Pack O' Shit"
author = "jammehcow"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f64a57787cd070689db68aebd216864acd2231858c5a0ded8ac91d3464936db"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
