name = "Nelly's Pack O' Shit"
author = "jammeh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98c49d08559ec192771ebe953d46219d2074b78769d60f5292adc4a9069b9d73"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
